num1 = input('Digite algo:')
print('O tipo primitivo desse valor é', type(num1))
print('É um numero?', num1.isnumeric())
print('Tem espaço?', num1.isspace())
print('Tem letras?', num1.isalpha())
print('Possue letras e numeros?', num1.isalnum())
print('Está em maiuscula?', num1.isupper())
print('Está em minuscula?', num1.islower())
print('Está em decimal?', num1.isdecimal())
