num1 = int(input('Digite algo:'))
print('O tipo primitivo desse valor é', type(num1))
print('É um numero?', num1.isnumeric)
print('Tem espaço?', num1.isspace)
print('Tem letras?', num1.isalpha)
print('Possue letras e numeros?', num1.isalnum)